apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config

  labels:
    app: userservice

data:
  GRPC_PORT: "50051"
  APP_ENV: "dev"

  # Database
  DB_DRIVER: "postgres"
  DB_HOST: "users-postgres"     
  DB_PORT: "5432"
  DB_MIGRATION_AUTO_RUN: "true"

