apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev



resources:
- namespace.yaml
- configmap
- secrets
- ingress.yaml
- ../../base/api-gateway
- ../../base/user
- ../../base/product
- ../../base/cart
- ../../base/order

images:
- name: abodiaa/apigateway
  newName: abodiaa/apigateway
  newTag: f0b27435cfc85f6584307c686d552dfdf34f8e4a
- name: abodiaa/cartservice
  newName: abodiaa/cartservice
  newTag: f0b27435cfc85f6584307c686d552dfdf34f8e4a
- name: abodiaa/orderservice
  newName: abodiaa/orderservice
  newTag: f0b27435cfc85f6584307c686d552dfdf34f8e4a
- name: abodiaa/productservice
  newName: abodiaa/productservice
  newTag: f0b27435cfc85f6584307c686d552dfdf34f8e4a
- name: abodiaa/userservice
  newName: abodiaa/userservice
  newTag: f0b27435cfc85f6584307c686d552dfdf34f8e4a

labels:
- includeSelectors: true
  pairs:
    env: dev





patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: api-gateway
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: userservice
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: productservice
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: cartservice
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: orderservice
